### ISSUE TITLE
Have Error

### ISSUE THREAD

**Issue by hyssopmopeds** [LuYee6813/PD_Cracker#1]
[](url
<img width="1084" alt="Screenshot 2022-04-21 at 19 41 08" src="https://user-images.githubusercontent.com/94949553/164509735-cfc04fde-9b0c-4a69-ae93-ffd0d60b92bc.png">
)

**Comment by LuYee6813** [comment]
vm name can't not have space like  "windows 11" must to "windows_11"

hyssopmopeds ***@***.***> 於 2022年4月22日 週五 上午12:42寫道：
